// <auto-generated />
namespace BA_Proje_DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ProductMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductMig));
        
        string IMigrationMetadata.Id
        {
            get { return "202005271304445_Product-Mig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
